/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardModifiersRouteImport } from './routes/dashboard/modifiers'
import { Route as DashboardMenuRouteImport } from './routes/dashboard/menu'
import { Route as DashboardItemsRouteImport } from './routes/dashboard/items'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardOrdersPaymentRouteImport } from './routes/dashboard/orders/payment'
import { Route as DashboardOrdersCookingRouteImport } from './routes/dashboard/orders/cooking'
import { Route as DashboardOrdersBaggingRouteImport } from './routes/dashboard/orders/bagging'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardModifiersRoute = DashboardModifiersRouteImport.update({
  id: '/modifiers',
  path: '/modifiers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardItemsRoute = DashboardItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersPaymentRoute = DashboardOrdersPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => DashboardOrdersRoute,
} as any)
const DashboardOrdersCookingRoute = DashboardOrdersCookingRouteImport.update({
  id: '/cooking',
  path: '/cooking',
  getParentRoute: () => DashboardOrdersRoute,
} as any)
const DashboardOrdersBaggingRoute = DashboardOrdersBaggingRouteImport.update({
  id: '/bagging',
  path: '/bagging',
  getParentRoute: () => DashboardOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/modifiers': typeof DashboardModifiersRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orders/bagging': typeof DashboardOrdersBaggingRoute
  '/dashboard/orders/cooking': typeof DashboardOrdersCookingRoute
  '/dashboard/orders/payment': typeof DashboardOrdersPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/modifiers': typeof DashboardModifiersRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/orders/bagging': typeof DashboardOrdersBaggingRoute
  '/dashboard/orders/cooking': typeof DashboardOrdersCookingRoute
  '/dashboard/orders/payment': typeof DashboardOrdersPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/modifiers': typeof DashboardModifiersRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orders/bagging': typeof DashboardOrdersBaggingRoute
  '/dashboard/orders/cooking': typeof DashboardOrdersCookingRoute
  '/dashboard/orders/payment': typeof DashboardOrdersPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/dashboard/home'
    | '/dashboard/items'
    | '/dashboard/menu'
    | '/dashboard/modifiers'
    | '/dashboard/orders'
    | '/dashboard/'
    | '/dashboard/orders/bagging'
    | '/dashboard/orders/cooking'
    | '/dashboard/orders/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/dashboard/home'
    | '/dashboard/items'
    | '/dashboard/menu'
    | '/dashboard/modifiers'
    | '/dashboard/orders'
    | '/dashboard'
    | '/dashboard/orders/bagging'
    | '/dashboard/orders/cooking'
    | '/dashboard/orders/payment'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/dashboard/home'
    | '/dashboard/items'
    | '/dashboard/menu'
    | '/dashboard/modifiers'
    | '/dashboard/orders'
    | '/dashboard/'
    | '/dashboard/orders/bagging'
    | '/dashboard/orders/cooking'
    | '/dashboard/orders/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/modifiers': {
      id: '/dashboard/modifiers'
      path: '/modifiers'
      fullPath: '/dashboard/modifiers'
      preLoaderRoute: typeof DashboardModifiersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/items': {
      id: '/dashboard/items'
      path: '/items'
      fullPath: '/dashboard/items'
      preLoaderRoute: typeof DashboardItemsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders/payment': {
      id: '/dashboard/orders/payment'
      path: '/payment'
      fullPath: '/dashboard/orders/payment'
      preLoaderRoute: typeof DashboardOrdersPaymentRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
    '/dashboard/orders/cooking': {
      id: '/dashboard/orders/cooking'
      path: '/cooking'
      fullPath: '/dashboard/orders/cooking'
      preLoaderRoute: typeof DashboardOrdersCookingRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
    '/dashboard/orders/bagging': {
      id: '/dashboard/orders/bagging'
      path: '/bagging'
      fullPath: '/dashboard/orders/bagging'
      preLoaderRoute: typeof DashboardOrdersBaggingRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
  }
}

interface DashboardOrdersRouteChildren {
  DashboardOrdersBaggingRoute: typeof DashboardOrdersBaggingRoute
  DashboardOrdersCookingRoute: typeof DashboardOrdersCookingRoute
  DashboardOrdersPaymentRoute: typeof DashboardOrdersPaymentRoute
}

const DashboardOrdersRouteChildren: DashboardOrdersRouteChildren = {
  DashboardOrdersBaggingRoute: DashboardOrdersBaggingRoute,
  DashboardOrdersCookingRoute: DashboardOrdersCookingRoute,
  DashboardOrdersPaymentRoute: DashboardOrdersPaymentRoute,
}

const DashboardOrdersRouteWithChildren = DashboardOrdersRoute._addFileChildren(
  DashboardOrdersRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardItemsRoute: typeof DashboardItemsRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardModifiersRoute: typeof DashboardModifiersRoute
  DashboardOrdersRoute: typeof DashboardOrdersRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardItemsRoute: DashboardItemsRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardModifiersRoute: DashboardModifiersRoute,
  DashboardOrdersRoute: DashboardOrdersRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
