/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmsTermsRouteImport } from './routes/sms-terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPaymentRouteImport } from './routes/dashboard/payment'
import { Route as DashboardModifiersRouteImport } from './routes/dashboard/modifiers'
import { Route as DashboardMenuRouteImport } from './routes/dashboard/menu'
import { Route as DashboardManualEntryRouteImport } from './routes/dashboard/manual-entry'
import { Route as DashboardItemsRouteImport } from './routes/dashboard/items'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardCookingRouteImport } from './routes/dashboard/cooking'
import { Route as DashboardBaggingRouteImport } from './routes/dashboard/bagging'

const SmsTermsRoute = SmsTermsRouteImport.update({
  id: '/sms-terms',
  path: '/sms-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPaymentRoute = DashboardPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardModifiersRoute = DashboardModifiersRouteImport.update({
  id: '/modifiers',
  path: '/modifiers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardManualEntryRoute = DashboardManualEntryRouteImport.update({
  id: '/manual-entry',
  path: '/manual-entry',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardItemsRoute = DashboardItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCookingRoute = DashboardCookingRouteImport.update({
  id: '/cooking',
  path: '/cooking',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBaggingRoute = DashboardBaggingRouteImport.update({
  id: '/bagging',
  path: '/bagging',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/dashboard/bagging': typeof DashboardBaggingRoute
  '/dashboard/cooking': typeof DashboardCookingRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard/manual-entry': typeof DashboardManualEntryRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/modifiers': typeof DashboardModifiersRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/dashboard/bagging': typeof DashboardBaggingRoute
  '/dashboard/cooking': typeof DashboardCookingRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard/manual-entry': typeof DashboardManualEntryRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/modifiers': typeof DashboardModifiersRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/my-orders': typeof MyOrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sms-terms': typeof SmsTermsRoute
  '/dashboard/bagging': typeof DashboardBaggingRoute
  '/dashboard/cooking': typeof DashboardCookingRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/items': typeof DashboardItemsRoute
  '/dashboard/manual-entry': typeof DashboardManualEntryRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/modifiers': typeof DashboardModifiersRoute
  '/dashboard/payment': typeof DashboardPaymentRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/my-orders'
    | '/privacy-policy'
    | '/sms-terms'
    | '/dashboard/bagging'
    | '/dashboard/cooking'
    | '/dashboard/home'
    | '/dashboard/items'
    | '/dashboard/manual-entry'
    | '/dashboard/menu'
    | '/dashboard/modifiers'
    | '/dashboard/payment'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/my-orders'
    | '/privacy-policy'
    | '/sms-terms'
    | '/dashboard/bagging'
    | '/dashboard/cooking'
    | '/dashboard/home'
    | '/dashboard/items'
    | '/dashboard/manual-entry'
    | '/dashboard/menu'
    | '/dashboard/modifiers'
    | '/dashboard/payment'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/my-orders'
    | '/privacy-policy'
    | '/sms-terms'
    | '/dashboard/bagging'
    | '/dashboard/cooking'
    | '/dashboard/home'
    | '/dashboard/items'
    | '/dashboard/manual-entry'
    | '/dashboard/menu'
    | '/dashboard/modifiers'
    | '/dashboard/payment'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MyOrdersRoute: typeof MyOrdersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SmsTermsRoute: typeof SmsTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sms-terms': {
      id: '/sms-terms'
      path: '/sms-terms'
      fullPath: '/sms-terms'
      preLoaderRoute: typeof SmsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payment': {
      id: '/dashboard/payment'
      path: '/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof DashboardPaymentRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/modifiers': {
      id: '/dashboard/modifiers'
      path: '/modifiers'
      fullPath: '/dashboard/modifiers'
      preLoaderRoute: typeof DashboardModifiersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/manual-entry': {
      id: '/dashboard/manual-entry'
      path: '/manual-entry'
      fullPath: '/dashboard/manual-entry'
      preLoaderRoute: typeof DashboardManualEntryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/items': {
      id: '/dashboard/items'
      path: '/items'
      fullPath: '/dashboard/items'
      preLoaderRoute: typeof DashboardItemsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/cooking': {
      id: '/dashboard/cooking'
      path: '/cooking'
      fullPath: '/dashboard/cooking'
      preLoaderRoute: typeof DashboardCookingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bagging': {
      id: '/dashboard/bagging'
      path: '/bagging'
      fullPath: '/dashboard/bagging'
      preLoaderRoute: typeof DashboardBaggingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardBaggingRoute: typeof DashboardBaggingRoute
  DashboardCookingRoute: typeof DashboardCookingRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardItemsRoute: typeof DashboardItemsRoute
  DashboardManualEntryRoute: typeof DashboardManualEntryRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardModifiersRoute: typeof DashboardModifiersRoute
  DashboardPaymentRoute: typeof DashboardPaymentRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardBaggingRoute: DashboardBaggingRoute,
  DashboardCookingRoute: DashboardCookingRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardItemsRoute: DashboardItemsRoute,
  DashboardManualEntryRoute: DashboardManualEntryRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardModifiersRoute: DashboardModifiersRoute,
  DashboardPaymentRoute: DashboardPaymentRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MyOrdersRoute: MyOrdersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SmsTermsRoute: SmsTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
